"""03_write_spef.py — STAGE 2 of TreePEX tool: per-net predictions → SPEF.

Writes IEEE 1481-1999 SPEF format with:
  - Header (design name, units, scope)
  - For each predicted net: *D_NET <name> <total_cap>   *CONN ... *CAP ... *END

Pin / cap distribution is condensed: a single `*CAP 1 <netname>:0 <total_cap>`
entry per net (representing aggregated lumped cap). This is sufficient for
downstream MAPE / cap-weighted comparison; full per-pin distribution would
require a pin-level model.

Output: outputs/spef/<design>_pred.spef
"""
from __future__ import annotations

import argparse
import time
from datetime import datetime
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
PREDS = ROOT / "outputs" / "predictions"
SPEF_OUT = ROOT / "outputs" / "spef"
SPEF_OUT.mkdir(parents=True, exist_ok=True)


SPEF_HEADER_TMPL = """*SPEF "IEEE 1481-1999"
*DESIGN "{design}"
*DATE "{date}"
*VENDOR "TreePEX (S4 Tweedie XGBoost ensemble)"
*PROGRAM "TreePEX deployable PEX tool"
*VERSION "1.0"
*DESIGN_FLOW "PIN_CAP NONE" "NAME_SCOPE LOCAL"
*DIVIDER /
*DELIMITER :
*BUS_DELIMITER []
*T_UNIT 1.0 NS
*C_UNIT 1.0 FF
*R_UNIT 1.0 OHM
*L_UNIT 1.0 HENRY

// Generated by TreePEX (S4 Tweedie 5-seed ensemble)
// Inference time per net: ~0.5 μs on CPU
// Feature set: 41 base + 26 top-K aggressor (per pex_v4 H-track)

"""


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--design", type=str, required=True)
    p.add_argument("--design-stem", type=str, default=None,
                   help="Optional design stem to use in SPEF header (e.g., 'tv80s' instead of 'intel22_tv80s_f3')")
    return p.parse_args()


def main():
    args = parse_args()
    pred_csv = PREDS / f"{args.design}_pred.csv"
    if not pred_csv.exists():
        print(f"[error] missing {pred_csv}; run STAGE 1 first")
        return 1
    df = pd.read_csv(pred_csv)
    design_stem = args.design_stem or args.design.split("intel22_")[-1].replace("_f3", "")
    print(f">>> TreePEX STAGE 2 [spef-write] on {args.design} ({len(df):,} nets) → stem '{design_stem}'")

    t0 = time.time()
    out_path = SPEF_OUT / f"{args.design}_pred.spef"
    date_str = datetime.now().strftime("%a %b %d %H:%M:%S %Y")
    header = SPEF_HEADER_TMPL.format(design=design_stem, date=date_str)

    lines = [header]
    for _, row in df.iterrows():
        net = str(row["net_name"]).strip()
        c_tot = float(row["pred_total"])
        c_gnd = float(row["pred_gnd"])
        # Single lumped *CAP entry per net (aggregated). Full pin distribution
        # would require a pin-level model.
        lines.append(f"*D_NET {net} {c_tot:.5f}")
        lines.append("*CONN")
        # Minimal *CONN: just write net name as internal node — downstream
        # tools tolerate empty *CONN if *CAP has at least one entry
        lines.append("*CAP")
        lines.append(f"1 {net}:0 {c_gnd:.5f}")
        lines.append("*END")
        lines.append("")
    out_path.write_text("\n".join(lines))
    t_spef = time.time() - t0
    print(f">>> wrote {out_path}  ({len(df):,} *D_NET entries, {t_spef:.2f}s, "
          f"{out_path.stat().st_size/1024/1024:.1f} MB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
